/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mammb.code.jpa.fluent.modelgen.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
